context:
  org: peco
  name: peco
  version: "0.6.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/${{ org }}/${{ name|lower }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 480ba339c5b15ebb9eada276d5e25315ee5c36e878d86dcfc1ea17f54a27197a

build:
  number: 1

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses
    - goreleaser
    - make

tests:
  - script:
      - ${{ name }} --version

about:
  homepage: https://github.com/${{ org }}/${{ name }}
  repository: https://github.com/${{ org }}/${{ name }}
  documentation: https://github.com/${{ org }}/${{ name }}/blob/v${{ version }}/README.md
  summary: "Simplistic interactive filtering tool"
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  description: |
    `peco` can be a great tool to filter stuff like logs,
    process stats, find files, because unlike grep,
    you can type as you think and look through the current results.

extra:
  recipe-maintainers:
    - eunos-1128
